CREATE TABLE EQUIPE (
	CD_EQUIPE INTEGER PRIMARY KEY,
	NOME_EQUIPE VARCHAR (50)
);

INSERT INTO EQUIPE(CD_EQUIPE, NOME_EQUIPE) VALUES(1, 'Informática');
INSERT INTO EQUIPE(CD_EQUIPE, NOME_EQUIPE) VALUES(2, 'TI');
INSERT INTO EQUIPE(CD_EQUIPE, NOME_EQUIPE) VALUES(3, 'RH');
INSERT INTO EQUIPE(CD_EQUIPE, NOME_EQUIPE) VALUES(4, 'Marketing');
INSERT INTO EQUIPE(CD_EQUIPE, NOME_EQUIPE) VALUES(5, 'Logística');
INSERT INTO EQUIPE(CD_EQUIPE, NOME_EQUIPE) VALUES(6, 'Infra');