CREATE TABLE FUNCIONARIO (
	CD_FUNC        INTEGER PRIMARY KEY,
	NM_FUNCIONARIO VARCHAR(50),
	RUA            VARCHAR(35),
	NUMERO         VARCHAR(20),
	COMPLEMENTO    VARCHAR(15),
	BAIRRO         VARCHAR(30),
	CIDADE         VARCHAR(30),
	ESTADO         VARCHAR(20)
);

INSERT INTO FUNCIONARIO(
	CD_FUNC 
   ,NM_FUNCIONARIO 
   ,RUA 
   ,NUMERO
   ,COMPLEMENTO
   ,BAIRRO
   ,CIDADE
   ,ESTADO
)
VALUES(10, 'GABRIEL', 'RUA DO SOSSEGO', '505-B', 'CASA', 'LIVRAMENTO', 'OLINDA', 'PERNAMBUCO');

INSERT INTO FUNCIONARIO(
	CD_FUNC 
   ,NM_FUNCIONARIO 
   ,RUA 
   ,NUMERO
   ,COMPLEMENTO
   ,BAIRRO
   ,CIDADE
   ,ESTADO
)
VALUES(20, 'MAURO', 'RUA DA SOLEDADE', '705', 'CASA', 'RECIFE', 'RECIFE', 'PERNAMBUCO');

INSERT INTO FUNCIONARIO(
	CD_FUNC 
   ,NM_FUNCIONARIO 
   ,RUA 
   ,NUMERO
   ,COMPLEMENTO
   ,BAIRRO
   ,CIDADE
   ,ESTADO
)
VALUES(30, 'GIOVANNA', 'RUA DO AMPARO', '10', 'CASA', 'AMPARO', 'OLINDA', 'PERNAMBUCO');

INSERT INTO FUNCIONARIO(
	CD_FUNC 
   ,NM_FUNCIONARIO 
   ,RUA 
   ,NUMERO
   ,COMPLEMENTO
   ,BAIRRO
   ,CIDADE
   ,ESTADO
)
VALUES(40, 'MARIANA', 'RUA DO CASARÃO', '547', 'CASA', 'PADRE ROMA', 'JABOATÃO DOS GUARARAPES', 'PERNAMBUCO');

