ALTER TABLE FUNCIONARIO
  ADD COLUMN CD_EQUIPE INTEGER;
  
ALTER TABLE FUNCIONARIO
  ADD COLUMN DT_CONTRATACAO DATE;  
 
 UPDATE FUNCIONARIO
 SET CD_EQUIPE = 2
 WHERE CD_FUNC IN (10, 20);
 
 UPDATE FUNCIONARIO
 SET CD_EQUIPE = 5
 WHERE CD_FUNC IN (30, 31, 40);
 
 UPDATE FUNCIONARIO
 SET DT_CONTRATACAO = '2018-01-01';
 
ALTER TABLE FUNCIONARIO
  ADD CONSTRAINT cd_equipe_fk FOREIGN KEY(CD_EQUIPE) REFERENCES EQUIPE(CD_EQUIPE);
	
ALTER TABLE FUNCIONARIO
  ALTER COLUMN DT_CONTRATACAO SET NOT NULL;